# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YQHPhotoBrowserDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YQHPhotoBrowserDemo

  target 'YQHPhotoBrowserDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YQHPhotoBrowserDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
